spring:
  # Configuration de la base de données
  datasource:
    url: jdbc:h2:mem:altenshop
    username: sa
    password: password
    driverClassName: org.h2.Driver

  # Configuration de H2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false

  # Configuration JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Configuration Jackson
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

# Configuration JWT
jwt:
  secret: votreCleSecreteTresLongueEtSecuriseeAuMoins256BitsDePreference
  expiration: 86400000  # 24 heures en millisecondes

# Configuration Logging
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.alten: DEBUG

# Configuration du serveur
server:
  port: 8080
  servlet:
    context-path: /api